<?php
// $Id$

/**
 * @file
 * LTI Consumer: expose a Drupal path to a third-party application
 */

/**
 * Implementation of hook_menu().
 */
function lti_consumer_menu () { 
  $items = array();

  $items['admin/settings/lti/consumer'] = array(
    'title' => 'LTI Consumer Settings',
    'page callback' => 'lti_consumer_admin',
    'access arguments' => array('TODO: Enter user permissions'),
  );
  $items['lti/%'] = array(
    'title' => 'LTI Consumer Settings',
    'page callback' => 'lti_consumer_page',
    'page arguments' => array(1),
    'access arguments' => array('TODO: Enter user permissions'),
  );

  return $items;
}

function lti_consumer_admin () {
  $lti_id = 0;
  if (arg(5)) {
    $lti_id = arg(5);
  }

  $form = drupal_get_form('lti_consumer_admin_form', array($lti_id));

  $header = array('Id', 'Name', 'Path', 'Key', 'Created', 'Updated', 'Preview', 'Edit', 'Delete');

  $res = db_query("SELECT * FROM {lti_consumer} ORDER BY id DESC");

  $rows = array();
  while ($r = $res) {
    $row = array();
    $row[] = $r->id;
    $row[] = $r->lti_name;
    $row[] = $r->lti_path;
    $row[] = $r->lti_key;
    $row[] = format_date($r->created, 'small');
    $row[] = format_date($r->updated, 'small');
    $row[] = l('Preview', 'lti/' . $r->id);
    $row[] = l('Edit', 'admin/settings/lti/consumer/edit/' . $r->id);
    $row[] = l('Delete', 'admin/settings/lti/consumer/delete/' . $r->id);

    $rows[] = $row;
  }

  return $form . theme('table', $header, $rows);
}

function lti_consumer_admin_form ($ignore, $lti_id) {
  $lti = null;
  if (isset($lti_id) && (int)$lti_id > 0) {
    $lti = db_query('SELECT * FROM {lti_consumer} WHERE id=:id', array(':id' => $lti_id));
  }

  $form = array();

  $form['lti'] = array(
    '#type' => 'fieldset',
    '#title' => 'New LTI Consumer',
  );

  $form['lti']['lti_name'] = array(
    '#type' => 'textfield',
    '#title' => 'Consumer Name',
    '#description' => 'A unqiue name for this LTI consumer',
    '#default_value' => (isset($lti) ? $lti->lti_name : ''),
    '#required' => TRUE,
  );
  $form['lti']['lti_path'] = array(
    '#type' => 'textfield',
    '#title' => 'Consumer Path',
    '#description' => 'The LTI tool path',
    '#default_value' => (isset($lti) ? $lti->lti_path : 'http://www.imsglobal.org/developers/BLTI/tool.php'),
    '#required' => TRUE,
  );
  $form['lti']['lti_key'] = array(
    '#type' => 'textfield',
    '#title' => 'Consumer Key',
    '#description' => 'The LTI consumer key',
    '#default_value' => (isset($lti) ? $lti->lti_key : 'lmsng.school.edu'),
    '#required' => TRUE,
  );
  $form['lti']['lti_secret'] = array(
    '#type' => 'textfield',
    '#title' => 'Consumer Secret',
    '#description' => 'The LTI consumer secret',
    '#default_value' => (isset($lti) ? $lti->lti_secret : '12345'),
    '#required' => TRUE,
  );

  $form['lti_id'] = array(
    '#type' => 'value',
    '#value' => (isset($lti) ? $lti->id : -1),
  );

  $form['lti']['submit'] = array(
    '#type' => 'submit',
    '#value' => 'Submit',
  );

  return $form;
}

function lti_consumer_admin_form_submit ($form_id, $form_state, $form_values) {
  $values = $form_state['values'];
  $lti_id = $values['lti_id'];

  if ($lti_id > 0) {
    // Update an existing LTI consumer
    db_query("UPDATE {lti_consumer} SET lti_name='%s', lti_path='%s', lti_key='%s', lti_secret='%s', updated=%d", 
      $values['lti_name'], $values['lti_path'], $values['lti_key'], $values['lti_secret'], time());
  }
  else {
    // Create a new LTI consumer
    db_query("INSERT INTO {lti_consumer} (lti_name, lti_path, lti_key, lti_secret, created, updated) VALUES ('%s', '%s', '%s', '%s', %d, %d)",
      $values['lti_name'], $values['lti_path'], $values['lti_key'], $values['lti_secret'], time(), time());
  }
}


function lti_consumer_page ($lti_id) {
  global $user;

  module_load_include('php', 'oauth_common', 'lib/OAuth');

  $lti = db_query("SELECT * FROM {lti_consumer} WHERE id=%d", $lti_id);

  $params = array(
      "resource_link_id" => $lti->id,
      "user_id" => $user->uid,
      "roles" => lti_consumer_get_ims_role($user),
      "lis_person_name_full" => $user->name,
      "lis_person_contact_email_primary" => $user->mail,
      "lis_person_sourcedid" => $user->uid,
      "context_id" => $_GET['q'],
      "context_title" => $lti->lti_name,
      "context_label" => $lti->lti_name,
      "oauth_callback" => "about:blank",
      "lti_version" => "LTI-1p0",
      "lti_message_type" => "lti-launch-request",
      "lti_submit" => "Launch Endpoint with lti Data",
  );
    
  $hmac_method = new OAuthSignatureMethod_HMAC_SHA1();
  $consumer = new OAuthConsumer($lti->lti_key, $lti->lti_secret, NULL);

  $req = OAuthRequest::from_consumer_and_token($consumer, '', 'POST', $lti->lti_path, $params);
  $req->sign_request($hmac_method, $consumer, '');

  // Pass this back up "out of band" for debugging
  //$last_base_string = $req->get_signature_base_string();

  $new_params = $req->get_parameters();

	$post = curl_init($lti->lti_path);
	curl_setopt($post, CURLOPT_HEADER, 1);
	curl_setopt($post, CURLOPT_POST, 1);
	curl_setopt($post, CURLOPT_POSTFIELDS, $new_params);
	curl_setopt($post, CURLOPT_RETURNTRANSFER, 1);

	$response = curl_exec($post);
	curl_close($post);
  return $response;
}

function lti_consumer_sign_parameters ($lti_path, $request_params) {
}

function lti_consumer_get_ims_role ($user) {
  return "Learner";
}
