<?php

/**
 * @file
 * LTI Consumer: expose a Drupal path to a third-party application
 */

/**
 * Implementation of hook_menu().
 */
function lti_consumer_menu () { 
  $items = array();

  $items['admin/settings/lti/consumer'] = array(
    'title' => 'LTI Consumer Admin Settings',
    'page callback' => 'lti_consumer_admin',
    'access arguments' => array('administer site configuration'),
  );
  $items['lti/%'] = array(
    'title' => 'LTI Consumer Settings',
    'page callback' => 'lti_consumer_page',
    'page arguments' => array(1),
    'access arguments' => array('access content'),
  );

  return $items;
}

function lti_consumer_admin () {
  $lti_id = 0;
  if (arg(5)) {
    $lti_id = arg(5);
  }

  //$form = drupal_get_form('lti_consumer_admin_form', $lti_id);
  
  $header = array('SID', 'Name', 'Domain', 'Key', 'Created', 'Updated', 'Preview', 'Edit', 'Delete');

  $res = db_query("SELECT * FROM {lti_consumer} ORDER BY sid ASC");

  $rows = array();
  foreach ($res as $r) {
    $row = array();
    $row[] = $r->sid;
    $row[] = $r->lti_name;
    $row[] = $r->lti_domain;
    $row[] = $r->lti_key;
    $row[] = format_date($r->created, 'small');
    $row[] = format_date($r->updated, 'small');
    $row[] = l('Preview', 'lti/' . $r->sid);
    $row[] = l('Edit', 'admin/settings/lti/consumer/edit/' . $r->sid);
    $row[] = l('Delete', 'admin/settings/lti/consumer/delete/' . $r->sid);

    $rows[] = $row;
  }
  
  //return drupal_get_form('lti_consumer_admin_form', $lti_id);
  return theme('table', array('header' => $header, 'rows' => $rows));
}

function lti_consumer_admin_form ($form, &$form_state, $lti_id) {
  $lti = null;
  if (isset($lti_id) && (int)$lti_id > 0) {
    $lti = db_query('SELECT * FROM {lti_consumer} WHERE sid = :sid', array(':sid' => $lti_id))->fetchObject();
  }

  //$form = array();

  $form['lti'] = array(
    '#type' => 'fieldset',
    '#title' => 'New LTI Consumer',
  );

  $form['lti']['lti_name'] = array(
    '#type' => 'textfield',
    '#title' => 'Consumer Name',
    '#description' => 'A unqiue name for this LTI consumer',
    '#default_value' => (isset($lti) ? $lti->lti_name : 'IMS Test Content'),
    '#required' => TRUE,
  );
  $form['lti']['lti_domain'] = array(
    '#type' => 'textarea',
    '#title' => 'Consumer Domain',
    '#description' => 'The LTI tool domain',
    '#default_value' => (isset($lti) ? $lti->lti_domain : 'http://www.imsglobal.org/developers/LTI/test/v1p1/tool.php'),
    '#required' => TRUE,
  );
  $form['lti']['lti_key'] = array(
    '#type' => 'textfield',
    '#title' => 'Consumer Key',
    '#description' => 'The LTI consumer key',
    '#default_value' => (isset($lti) ? $lti->lti_key : '12345'),
    '#required' => TRUE,
  );
  $form['lti']['lti_secret'] = array(
    '#type' => 'textfield',
    '#title' => 'Consumer Secret',
    '#description' => 'The LTI consumer secret',
    '#default_value' => (isset($lti) ? $lti->lti_secret : 'secret'),
    '#required' => TRUE,
  );

  $form['lti_id'] = array(
    '#type' => 'value',
    '#value' => (isset($lti) ? $lti->sid : -1),
  );

  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => 'Submit',
  );

  return $form;

}

function lti_consumer_admin_form_submit ($form_id, $form_state) {
  $values = $form_state['values'];
  $lti_id = $values['lti_id'];

  if ($lti_id > 0) {
    // Update an existing LTI consumer
    db_update('lti_consumer')
    ->fields(array(
    	'lti_name' => $values['lti_name'],
    	'lti_domain' => $values['lti_domain'],
    	'lti_key' => $values['lti_key'],
    	'lti_secret' => $values['lti_secret'],
    	'updated' => REQUEST_TIME,
    	))
    ->condition('sid', $lti_id, '=')
    ->execute();
  }
  else {
    // Create a new LTI consumer
    db_insert('lti_consumer')
    ->fields(array(
    	'lti_name' => $values['lti_name'],
    	'lti_domain' => $values['lti_domain'],
    	'lti_key' => $values['lti_key'],
    	'lti_secret' => $values['lti_secret'],
    	'created' => REQUEST_TIME,
    	'updated' => REQUEST_TIME,
    	))
    ->execute();
  }
}

function lti_consumer_page ($lti_id, $database_table='webform_views_add_lti_content_9') {
  	global $user;

 	 module_load_include('php', 'oauth_common', 'lib/OAuth');
 	 
 	//	Allow user to call another LTI table or use consumer table
 	$database_table = ($database_table) ? $database_table : 'lti_consumer';
  
  	//	query Database for selected LTI info
	$lti = db_query('SELECT * FROM {' . $database_table . '} WHERE sid = :sid', array(':sid' => $lti_id))->fetchObject();
  
  	//	parameters for LTI Consumer
  	$params = array(
      "resource_link_id" => $lti->sid,
      "roles" => "Instructor",
      "user_id" => $user->uid,
      "lis_person_name_full" => $user->name,
      "lis_person_contact_email_primary" => $user->mail,
      "lis_person_sourcedid" => $user->uid,
      "context_id" => $_GET['q'],
      "context_title" => $lti->name,
      "context_label" => $lti->name,
      "oauth_callback" => "about:blank",
      "lti_version" => "LTI-1p0",
      "lti_message_type" => "basic-lti-launch-request",
      "lti_submit" => "Launch Endpoint with LTI Data");
      
	//	set OAuth requirements to LTI info
	$domain = $lti->domain;
	$consumer_key = $lti->consumer_key;
	$consumer_secret = $lti->shared_secret;
	
	//	create OAuthConsumer
	$consumer = new OAuthConsumer($consumer_key, $consumer_secret);
	
	//	create Signature Method
	$signature = new OAuthSignatureMethod_HMAC_SHA1();
	
	//	create Oauth
	$oauth = OAuthRequest::from_consumer_and_token($consumer, '', 'POST', $domain, $params);
	
	//	request Signature for OAuth
	$oauth->sign_request($signature, $consumer, '');
	
	//	call OAuth and display on webpage
	$post = curl_init($oauth);

	//	remove comment below to view LTI Header
 
	//curl_setopt($post, CURLOPT_HEADER, 1);
	
	curl_setopt($post, CURLOPT_POST, 1);
	curl_setopt($post, CURLOPT_POSTFIELDS, $params);
	curl_exec($post);
	curl_close($post);
	
}
